import numpy.testing as npt 
from projectetl.utils.config import data_dir
import pandas as pd 
import numpy as np 
from export.exp0_export import(
    export_name_transformer,
    format_varibles
)
df_export_municipaily_processed = pd.read_csv( f'data/testData/export/mepyd_municipality_20210927_test.csv')
df_export_neighborhood_processed = pd.read_csv( f'data/testData/export/mepyd_neighborhoods_20210927_test.csv')
#MUNICIPALITY

def test_shape_end_rodrigo_integration_neighborhood():
    assert df_export_neighborhood_processed.shape ==(12565, 132)
    
def test_describe_end_rodrigo_integration_neighborhood():
    df_describe =  df_export_neighborhood_processed.describe()
    internal_dict = df_describe.loc['mean'].to_dict() 
    external_dict = {'ratio parcial de dependencia (0 a 4)': 0.0,
    'proporcion hogares 0 a 4': 0.0,
    'ratio total de dependencia (0 a 4)': 0.0,
    'ratio parcial de dependencia (5 a 12)': 0.0,
    'proporcion hogares (5 a 12)': 0.0,
    'ratio total de dependencia (5 a 12)': 0.0,
    'ratio parcial de dependencia (discapacitados 5 a 64)': 0.0,
    'proporcion hogares discapacitados 5 a 64': 0.0,
    'ratio total de dependencia (discapacitados 5 a 64)': 0.0,
    'ratio parcial de dependencia (discapacitados 13 a 64)': 0.0,
    'proporcion hogares discapacitado 13 a 64': 0.0,
    'ratio total de dependencia (discapacitados 13 a 64)': 0.0,
    'ratio parcial de dependencia(envejecientes)': 0.0,
    'proporcion hogares envejecientes': 0.0,
    'ratio total de dependencia (envejecientes)': 0.0,
    'ratio parcial de dependencia grave (envejecientes)': 0.0,
    'proporcion hogares envejecientes dependencia grave': 0.0,
    'ratio total de dependencia grave (envejecientes)': 0.0,
    'ratio parcial de dependencia agregada': 0.0,
    'proporcion hogares dependencia agregada': 0.0,
    'ratio total de dependencia agregada': 0.0,
    'ratio parcial de dependencia agregada sin 5 a 12': 0.0,
    'proporcion hogares dependencia agregada sin 5 a 12': 0.0,
    'ratio total de dependencia agregada sin 5 a 12': 0.0,
    'ratio parcial de dependencia agregada sin env dep leves': 0.0,
    'proporcion hogares dependencia agregada sin env dep leves': 0.0,
    'ratio total de dependencia agregada sin env dep leves': 0.0,
    'ratio parcial de dependencia agregada sin 5 a 12 ni env dep leves': 0.0,
    'proporcion hogares dependencia agregada sin 5 a 12 ni env dep leves': 0.0,
    'ratio total de dependencia agregada sin 5 a 12 ni env dep leves total': 0.0,
    'N de personas de 0 a 4': 0.0,
    'N 0 a 4 en CAIPI': 0.0,
    'N de 0 a 4 en otros públicos': 0.0,
    'N de 0 a 4 en privados': 0.0,
    'N de 0 a 4 en otros': 0.0,
    'N de personas de 5 a 12': 0.0,
    'N de 5 a 12 sin s c ni tanda escolar completa': 0.0,
    'N de discapacitados (13 a 64)': 0.0,
    'N de adultos mayores dependientes graves': 0.0,
    'N personas superate': 0.0,
    'N hogares con miembros de 0 a 4 sin s c ni tanda escolar completa': 0.0,
    'N hogares con miembros de 5 a 12 sin s c ni tanda escolar completa': 0.0,
    'N hogares con miembros discapacitados (5 a 64)': 0.0,
    'N hogares con miembros discapacitados (13 a 64)': 0.0,
    'N hogares con miembros adultos mayores dependientes': 0.0,
    'N hogares con miembros adultos mayores dependientes graves': 0.0,
    'N de hogares con trabajadores domésticos': 0.0,
    'proporcion hogares con trabajadores domésticos': 0.0,
    'N de mujeres en edad de trabajar': 0.0,
    'proporcion de mujeres trabajadoras domésticas': 0.0,
    'N de trabajadores domésticos': 0.0,
    'N de hombres en edad de trabajar': 0.0,
    'proporcion de hombres trabajadores domésticos': 0.0,
    'idc-demanda de ciudado': 0.0,
    'idc-presencia de ciudadoras': 0.0,
    'idc-pobreza': 0.0,
    'indice de demanda de cuidados': 0.0,
    'capacidad total (CAIPI)': 1.9203313330680718,
    'N de 0 a 4 con a en trans': 0.0,
    'proporcion de 0 a 4 con a en trans': 0.0,
    'capacidad total (CCPP CON EPES)': 0.0,
    'N de 0 a 4 con a en trans (CCPP CON EPES)': 0.0,
    'proporcion de 0 a 4 con a en trans(CCPP CON EPES)': 0.0,
    'capacidad total (CTC CON EPES)': 0.0751262395543182,
    'capacidad total (ASFL DIURNAS)': 0.051549637883008814,
    'N env dep con aceso en transporte (ASFL DIURNAS)': 0.0,
    'proporcion env dep con aceso en transporte (ASFL DIURNAS)': 0.0,
    'N env dep grave con a en trans (ASFL DIURNAS)': 0.0,
    'proporcion env dep grave con a en trans (ASFL DIURNAS)': 0.0,
    'capacidad total (ASFL PERMANENTES)': 0.0391648229208114,
    'N env dep con aceso en transporte (ASFL PERMANENTES)': 0.0,
    'proporcion env dep con aceso en transporte (ASFL PERMANENTES)': 0.0,
    'N env dep grave con a en trans (ASFL PERMANENTES)': 0.0,
    'proporcion env dep grave con a en trans (ASFL PERMANENTES)': 0.0,
    'capacidad total (ESTANCIAS CONAPE)': 0.0117428889773179,
    'N env dep con aceso en transporte (ESTANCIAS CONAPE)': 0.0,
    'proporcion env dep con aceso en transporte (ESTANCIAS CONAPE)': 0.0,
    'N env dep grave con a en trans (ESTANCIAS CONAPE)': 0.0,
    'proporcion env dep grave con a en trans (ESTANCIAS CONAPE)': 0.0,
    'capacidad total (Nuevos C. de Dia CONAPE)': 0.0,
    'N env dep con aceso en transporte (Nuevos C. de Dia CONAPE)': 0.0,
    'proporcion env dep con aceso en transporte (Nuevos C. de Dia CONAPE)': 0.0,
    'N env dep grave con a en trans (Nuevos C. de Dia CONAPE)': 0.0,
    'proporcion env dep grave con a en trans (Nuevos C. de Dia CONAPE)': 0.0,
    'capacidad total (Centros CONAPE)': 0.19892768802228317,
    'N  CCPP SIN EPES': 0.000715718265021885,
    'N  COS INFOTEP': 0.007113410266613536,
    'N Direccion Regional INFOTEP': 0.0,
    'N Direccion Regional PROSOLI': 5.4994031038599326e-05,
    'N CAID': 0.0,
    'N Oficina de la Mujer': 0.002053004377238346,
    'Cobertura Superate': 0.0,
    'Cobertura max capacidad CAIPI': 0.0,
    'Ranking cob max capacidad CAIPI': 0.0,
    'Cobertura max capacidad CCPP CON EPES': 0.0,
    'Ranking cob max capacidad CCPP CON EPES': 0.0,
    'Cobertura max numero CCPP SIN EPES': 0.0,
    'Ranking cob max numero CCPP SIN EPES': 0.0,
    'Cobertura max capacidad  CTC CON EPES': 0.0,
    'Ranking cob max capacidad  CTC CON EPES': 0.0,
    'Cobertura max numero Direccion Regional PROSOLI': 0.0,
    'Ranking cob max numero Direccion Regional PROSOLI': 0.0,
    'Cobertura max capacidad CONAPE': 0.0,
    'Ranking cob max capacidad CONAPE': 0.0,
    'Cobertura max numero CAID': 0.0,
    'Ranking cob max numero CAID': 0.0,
    'Cobertura max numero Oficina de la Mujer': 0.0,
    'Ranking cob max numero Oficina de la Mujer': 0.0,
    'Cobertura max numero centros COS INFOTEP': 0.0,
    'Ranking cob max numero centros COS INFOTEP': 0.0,
    'Cobertura max numero Direccion Regional INFOTEP': 0.0,
    'Ranking cob max numero Direccion Regional INFOTEP': 0.0,
    'indice de cobertura institucional': 0.0,
    'Ranking indice de cobertura institucional': 0.0,
    'indice de oferta institucional': 0.24588141663350574,
    'Ranking indice de oferta institucional': 6283.0,
    'N de discapacitados (5 a 64)': 0.0,
    'N de 0 a 4 sin s c ni tanda escolar completa de cuidados': 0.0,
    'N de adultos mayores dependientes': 0.0,
    'N Casas monomarentales con niños': 0.0,
    'N Casas monomarentales con discapacitados': 0.0,
    'N Casas monomarentales con  envejecientes': 0.0,
    'N de trabajadoras domésticas': 0.0,
    'N hogares beneficiarios superate': 0.0,
    'porcentaje de mujeres pobres': 0.0,
    'procentaje de hogares pobres': 0.0,
    'N Mujeres pobres': 0.0,
    'N Casas pobres': 0.0,
    'Total de mujeres': 0.0}
    for k in internal_dict.keys():
        if k in external_dict.keys():
            if external_dict[k] ==0:
                diff = internal_dict[k]
            else:
                diff = np.abs((internal_dict[k]-external_dict[k])/ external_dict[k])
            assert diff< .005
   
   
#NEIGHBORHOOD
def test_shape_end_rodrigo_integration_municipality():
    assert df_export_municipaily_processed.shape ==(155, 131)
    
def test_describe_end_rodrigo_integration_municipality():
    assert True
    
    df_describe =  df_export_municipaily_processed.describe()
    internal_dict = df_describe.loc['mean'].to_dict() 
    external_dict = {'ratio parcial de dependencia (0 a 4)': 0.0,
    'proporcion hogares 0 a 4': 0.0,
    'ratio total de dependencia (0 a 4)': 0.0,
    'ratio parcial de dependencia (5 a 12)': 0.0,
    'proporcion hogares (5 a 12)': 0.0,
    'ratio total de dependencia (5 a 12)': 0.0,
    'ratio parcial de dependencia (discapacitados 5 a 64)': 0.0,
    'proporcion hogares discapacitados 5 a 64': 0.0,
    'ratio total de dependencia (discapacitados 5 a 64)': 0.0,
    'ratio parcial de dependencia (discapacitados 13 a 64)': 0.0,
    'proporcion hogares discapacitado 13 a 64': 0.0,
    'ratio total de dependencia (discapacitados 13 a 64)': 0.0,
    'ratio parcial de dependencia(envejecientes)': 0.0,
    'proporcion hogares envejecientes': 0.0,
    'ratio total de dependencia (envejecientes)': 0.0,
    'ratio parcial de dependencia grave (envejecientes)': 0.0,
    'proporcion hogares envejecientes dependencia grave': 0.0,
    'ratio total de dependencia grave (envejecientes)': 0.0,
    'ratio parcial de dependencia agregada': 0.0,
    'proporcion hogares dependencia agregada': 0.0,
    'ratio total de dependencia agregada': 0.0,
    'ratio parcial de dependencia agregada sin 5 a 12': 0.0,
    'proporcion hogares dependencia agregada sin 5 a 12': 0.0,
    'ratio total de dependencia agregada sin 5 a 12': 0.0,
    'ratio parcial de dependencia agregada sin env dep leves': 0.0,
    'proporcion hogares dependencia agregada sin env dep leves': 0.0,
    'ratio total de dependencia agregada sin env dep leves': 0.0,
    'ratio parcial de dependencia agregada sin 5 a 12 ni env dep leves': 0.0,
    'proporcion hogares dependencia agregada sin 5 a 12 ni env dep leves': 0.0,
    'ratio total de dependencia agregada sin 5 a 12 ni env dep leves total': 0.0,
    'N de personas de 0 a 4': 0.0,
    'N 0 a 4 en CAIPI': 0.0,
    'N de 0 a 4 en otros públicos': 0.0,
    'N de 0 a 4 en privados': 0.0,
    'N de 0 a 4 en otros': 0.0,
    'N de personas de 5 a 12': 0.0,
    'N de 5 a 12 sin s c ni tanda escolar completa': 0.0,
    'N de discapacitados (13 a 64)': 0.0,
    'N de adultos mayores dependientes graves': 0.0,
    'N personas superate': 0.0,
    'N hogares con miembros de 0 a 4 sin s c ni tanda escolar completa': 0.0,
    'N hogares con miembros de 5 a 12 sin s c ni tanda escolar completa': 0.0,
    'N hogares con miembros discapacitados (5 a 64)': 0.0,
    'N hogares con miembros discapacitados (13 a 64)': 0.0,
    'N hogares con miembros adultos mayores dependientes': 0.0,
    'N hogares con miembros adultos mayores dependientes graves': 0.0,
    'N de hogares con trabajadores domésticos': 0.0,
    'proporcion hogares con trabajadores domésticos': 0.0,
    'N de mujeres en edad de trabajar': 0.0,
    'proporcion de mujeres trabajadoras domésticas': 0.0,
    'N de trabajadores domésticos': 0.0,
    'N de hombres en edad de trabajar': 0.0,
    'proporcion de hombres trabajadores domésticos': 0.0,
    'idc-demanda de ciudado': 0.0,
    'idc-presencia de ciudadoras': 0.0,
    'idc-pobreza': 0.0,
    'indice de demanda de cuidados': 0.0,
    'capacidad total (CAIPI)': 1.9203313330680718,
    'N de 0 a 4 con a en trans': 0.0,
    'proporcion de 0 a 4 con a en trans': 0.0,
    'capacidad total (CCPP CON EPES)': 0.0,
    'N de 0 a 4 con a en trans (CCPP CON EPES)': 0.0,
    'proporcion de 0 a 4 con a en trans(CCPP CON EPES)': 0.0,
    'capacidad total (CTC CON EPES)': 0.0751262395543182,
    'capacidad total (ASFL DIURNAS)': 0.051549637883008814,
    'N env dep con aceso en transporte (ASFL DIURNAS)': 0.0,
    'proporcion env dep con aceso en transporte (ASFL DIURNAS)': 0.0,
    'N env dep grave con a en trans (ASFL DIURNAS)': 0.0,
    'proporcion env dep grave con a en trans (ASFL DIURNAS)': 0.0,
    'capacidad total (ASFL PERMANENTES)': 0.0391648229208114,
    'N env dep con aceso en transporte (ASFL PERMANENTES)': 0.0,
    'proporcion env dep con aceso en transporte (ASFL PERMANENTES)': 0.0,
    'N env dep grave con a en trans (ASFL PERMANENTES)': 0.0,
    'proporcion env dep grave con a en trans (ASFL PERMANENTES)': 0.0,
    'capacidad total (ESTANCIAS CONAPE)': 0.0117428889773179,
    'N env dep con aceso en transporte (ESTANCIAS CONAPE)': 0.0,
    'proporcion env dep con aceso en transporte (ESTANCIAS CONAPE)': 0.0,
    'N env dep grave con a en trans (ESTANCIAS CONAPE)': 0.0,
    'proporcion env dep grave con a en trans (ESTANCIAS CONAPE)': 0.0,
    'capacidad total (Nuevos C. de Dia CONAPE)': 0.0,
    'N env dep con aceso en transporte (Nuevos C. de Dia CONAPE)': 0.0,
    'proporcion env dep con aceso en transporte (Nuevos C. de Dia CONAPE)': 0.0,
    'N env dep grave con a en trans (Nuevos C. de Dia CONAPE)': 0.0,
    'proporcion env dep grave con a en trans (Nuevos C. de Dia CONAPE)': 0.0,
    'capacidad total (Centros CONAPE)': 0.19892768802228317,
    'N  CCPP SIN EPES': 0.000715718265021885,
    'N  COS INFOTEP': 0.007113410266613536,
    'N Direccion Regional INFOTEP': 0.0,
    'N Direccion Regional PROSOLI': 5.4994031038599326e-05,
    'N CAID': 0.0,
    'N Oficina de la Mujer': 0.002053004377238346,
    'Cobertura Superate': 0.0,
    'Cobertura max capacidad CAIPI': 0.0,
    'Ranking cob max capacidad CAIPI': 0.0,
    'Cobertura max capacidad CCPP CON EPES': 0.0,
    'Ranking cob max capacidad CCPP CON EPES': 0.0,
    'Cobertura max numero CCPP SIN EPES': 0.0,
    'Ranking cob max numero CCPP SIN EPES': 0.0,
    'Cobertura max capacidad  CTC CON EPES': 0.0,
    'Ranking cob max capacidad  CTC CON EPES': 0.0,
    'Cobertura max numero Direccion Regional PROSOLI': 0.0,
    'Ranking cob max numero Direccion Regional PROSOLI': 0.0,
    'Cobertura max capacidad CONAPE': 0.0,
    'Ranking cob max capacidad CONAPE': 0.0,
    'Cobertura max numero CAID': 0.0,
    'Ranking cob max numero CAID': 0.0,
    'Cobertura max numero Oficina de la Mujer': 0.0,
    'Ranking cob max numero Oficina de la Mujer': 0.0,
    'Cobertura max numero centros COS INFOTEP': 0.0,
    'Ranking cob max numero centros COS INFOTEP': 0.0,
    'Cobertura max numero Direccion Regional INFOTEP': 0.0,
    'Ranking cob max numero Direccion Regional INFOTEP': 0.0,
    'indice de cobertura institucional': 0.0,
    'Ranking indice de cobertura institucional': 0.0,
    'indice de oferta institucional': 0.24588141663350574,
    'Ranking indice de oferta institucional': 6283.0,
    'N de discapacitados (5 a 64)': 0.0,
    'N de 0 a 4 sin s c ni tanda escolar completa de cuidados': 0.0,
    'N de adultos mayores dependientes': 0.0,
    'N Casas monomarentales con niños': 0.0,
    'N Casas monomarentales con discapacitados': 0.0,
    'N Casas monomarentales con  envejecientes': 0.0,
    'N de trabajadoras domésticas': 0.0,
    'N hogares beneficiarios superate': 0.0,
    'porcentaje de mujeres pobres': 0.0,
    'procentaje de hogares pobres': 0.0,
    'N Mujeres pobres': 0.0,
    'N Casas pobres': 0.0,
    'Total de mujeres': 0.0}
    for k in internal_dict.keys():
        if k in external_dict.keys():
            if external_dict[k] ==0:
                diff = internal_dict[k]
            else:
                diff = np.abs((internal_dict[k]-external_dict[k])/ external_dict[k])
            assert diff< .005
   